[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm-migration = "2.0.0-rc.5"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "migration"
path = "src/main.rs"
